<a href="https://colab.research.google.com/github/lstarke/flai_analise_exploratoria_de_dados/blob/main/FLAI_An%C3%A1lise_Explorat%C3%B3ria_de_Dados_em_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Dicionários

dicionario = {'nome': 'Leandro', 
              'idade': 37, 
              'comida_favorita':'hamburgues'}

dicionario

{'comida_favorita': 'hamburgues', 'idade': 37, 'nome': 'Leandro'}

In [3]:
dicionario['nome']

'Leandro'

In [4]:
dicionario.items()

dict_items([('nome', 'Leandro'), ('idade', 37), ('comida_favorita', 'hamburgues')])

In [5]:
dicionario.keys()

dict_keys(['nome', 'idade', 'comida_favorita'])

In [6]:
dicionario.values()

dict_values(['Leandro', 37, 'hamburgues'])

In [7]:
parametros = {'loc': 0,  'scale': 1, 'size': 10}

In [8]:
import numpy as np

In [11]:
np.random.normal(**parametros) # ** usa dicionário

array([-0.06173593, -0.76548872,  0.9689037 ,  0.01200519, -0.75731042,
       -0.79001855,  0.68519468, -1.40272477,  0.13243199,  1.2587707 ])

In [12]:
np.random.normal(*[0, 1, 10]) # * usa lista

array([-1.07568008,  1.14418579,  0.74266608, -1.18942595,  0.10570982,
       -0.20993152,  0.00757355,  0.78491763, -0.17745868,  0.35198067])

---

In [13]:
# Pandas
# Dataframe
# Series

import pandas as pd

In [18]:
notas = np.random.uniform(low=0, high=10, size=30).round(1).reshape(10,3)
notas

array([[6.1, 3.7, 4.7],
       [5.8, 9.4, 4.2],
       [6.2, 6.7, 6.8],
       [1.5, 1.8, 5.2],
       [6.6, 9.5, 8. ],
       [5.5, 4.4, 0.7],
       [4.6, 5.9, 8.2],
       [1.5, 6.2, 2.6],
       [2.9, 3.9, 8.5],
       [9.2, 7.7, 9.4]])

In [20]:
provas = ['P1', 'P2', 'P3']
alunos = ['Alice', 'Bruno', 'Carla', 'David', 'Emily', 'Fábio', 'Gloria', 'Helio', 'Isabela', 'Lucas']

In [23]:
notas_alunos = pd.DataFrame(data=notas, index=alunos , columns=provas)

In [35]:
notas_alunos.head()

P1   P2   P3
Alice  6.1  3.7  4.7
Bruno  5.8  9.4  4.2
Carla  6.2  6.7  6.8
David  1.5  1.8  5.2
Emily  6.6  9.5  8.0

In [24]:
notas_alunos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Alice to Lucas
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   P1      10 non-null     float64
 1   P2      10 non-null     float64
 2   P3      10 non-null     float64
dtypes: float64(3)
memory usage: 320.0+ bytes


In [25]:
notas_alunos.describe()

P1         P2         P3
count  10.000000  10.000000  10.000000
mean    4.990000   5.920000   5.830000
std     2.422327   2.518289   2.832765
min     1.500000   1.800000   0.700000
25%     3.325000   4.025000   4.325000
50%     5.650000   6.050000   6.000000
75%     6.175000   7.450000   8.150000
max     9.200000   9.500000   9.400000

In [27]:
notas_alunos.transpose()

Alice  Bruno  Carla  David  Emily  Fábio  Gloria  Helio  Isabela  Lucas
P1    6.1    5.8    6.2    1.5    6.6    5.5     4.6    1.5      2.9    9.2
P2    3.7    9.4    6.7    1.8    9.5    4.4     5.9    6.2      3.9    7.7
P3    4.7    4.2    6.8    5.2    8.0    0.7     8.2    2.6      8.5    9.4

In [28]:
notas_alunos.transpose().describe()

Alice     Bruno     Carla  ...     Helio   Isabela     Lucas
count  3.000000  3.000000  3.000000  ...  3.000000  3.000000  3.000000
mean   4.833333  6.466667  6.566667  ...  3.433333  5.100000  8.766667
std    1.205543  2.663331  0.321455  ...  2.458319  2.986637  0.929157
min    3.700000  4.200000  6.200000  ...  1.500000  2.900000  7.700000
25%    4.200000  5.000000  6.450000  ...  2.050000  3.400000  8.450000
50%    4.700000  5.800000  6.700000  ...  2.600000  3.900000  9.200000
75%    5.400000  7.600000  6.750000  ...  4.400000  6.200000  9.300000
max    6.100000  9.400000  6.800000  ...  6.200000  8.500000  9.400000

[8 rows x 10 columns]

In [29]:
notas_alunos.shape

(10, 3)

In [31]:
notas_alunos['P1'] # quando é uma coluna do dataframe o tipo é Series

Alice      6.1
Bruno      5.8
Carla      6.2
David      1.5
Emily      6.6
Fábio      5.5
Gloria     4.6
Helio      1.5
Isabela    2.9
Lucas      9.2
Name: P1, dtype: float64

In [33]:
notas_alunos.mean(axis=0) # axis = 0 é colunas

P1    4.99
P2    5.92
P3    5.83
dtype: float64

In [34]:
notas_alunos.mean(axis=1) # axis = 1 é linhas

Alice      4.833333
Bruno      6.466667
Carla      6.566667
David      2.833333
Emily      8.033333
Fábio      3.533333
Gloria     6.233333
Helio      3.433333
Isabela    5.100000
Lucas      8.766667
dtype: float64

In [37]:
# adiciona nova coluna ao dataframe
# calcula a média de notas dos alunos
notas_alunos['media_final'] = notas_alunos.mean(axis=1).round(1)
notas_alunos.head()

P1   P2   P3  media_final
Alice  6.1  3.7  4.7          4.8
Bruno  5.8  9.4  4.2          6.5
Carla  6.2  6.7  6.8          6.6
David  1.5  1.8  5.2          2.8
Emily  6.6  9.5  8.0          8.0